'use client';
import { useCallback,useEffect,useState } from 'react';
import { toast } from 'sonner';
import { PROSPECT_STAGES,type Prospect } from '@/lib/prospect-types';
// Types and stage constants are client-safe; server storage never enters this module.
export default function ProspectPanel(){
  const [saved,setSaved]=useState<Prospect[]>([]),[results,setResults]=useState<Prospect[]>([]),[chosen,setChosen]=useState<string[]>([]);
  const [configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[domains,setDomains]=useState(''),[titles,setTitles]=useState('CIO, Chief Medical Information Officer, IT Director'),[locations,setLocations]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState<number|null>(null);
  const load=useCallback(async()=>{const r=await fetch('/api/prospects',{cache:'no-store'});if(!r.ok)throw Error('Prospects unavailable');const d=await r.json();setSaved(d.prospects);setConfigured(d.apolloConfigured);},[]);
  useEffect(()=>{load().catch(e=>toast.error(e.message));},[load]);
  async function search(){setBusy(true);setResults([]);setChosen([]);try{const split=(v:string)=>v.split(',').map(s=>s.trim()).filter(Boolean);const r=await fetch('/api/apollo/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domains:split(domains),titles:split(titles),locations:split(locations),page})});const d=await r.json();if(!r.ok)throw Error(d.error);setResults(d.people);setTotal(d.total);toast.success(`${d.people.length} results for review`);}catch(e){toast.error(e instanceof Error?e.message:'Search failed');}finally{setBusy(false);}}
  async function save(){setBusy(true);try{const people=results.filter(p=>chosen.includes(p.id)).map(p=>({id:p.id,name:p.name,title:p.title,organization:{name:p.organization,primary_domain:p.domain}}));const r=await fetch('/api/prospects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({people})});const d=await r.json();if(!r.ok)throw Error(d.error);await load();setChosen([]);toast.success(`${d.added} saved; ${d.duplicates} duplicates retained; ${d.blockedExistingClient??0} client matches blocked`);}catch(e){toast.error(e instanceof Error?e.message:'Import failed');}finally{setBusy(false);}}
  async function patch(p:Prospect,patch:{stage?:Prospect['stage'];notes?:string}){try{const r=await fetch(`/api/prospects/${encodeURIComponent(p.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...patch,version:p.version})});const d=await r.json();if(!r.ok)throw Error(d.error);setSaved(cur=>cur.map(x=>x.id===p.id?d.prospect:x));toast.success('Prospect saved');}catch(e){toast.error(e instanceof Error?e.message:'Save failed');await load();}}
  function exportSaved(){const cell=(v:string)=>'"'+(/^[\s]*[=+@-]/.test(v)?"'"+v:v).replaceAll('"','""')+'"';const rows=[['Name','Title','Organization','Domain','Stage','Notes','Apollo ID','Imported at','Client screening'],...saved.map(p=>[p.name,p.title,p.organization,p.domain,p.stage,p.notes,p.id,p.importedAt,p.clientCheck?.reason??"Not checked"])];const url=URL.createObjectURL(new Blob([rows.map(row=>row.map(cell).join(',')).join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='keena-apollo-prospects.csv';a.click();URL.revokeObjectURL(url);}
  return <section className="prospect-panel" id="apollo"><p className="eyebrow">ACCOUNT &amp; CONTACT DISCOVERY</p><h2>Apollo prospect workspace</h2><p>{configured?'API key configured — account access is verified when you search.':'Ready for setup — add APOLLO_API_KEY to your local environment.'} Prospects remain separate from opportunity evidence. Search does not reveal email or phone details.</p>
    <div className="discovery-fields"><label>Healthcare company domains (comma separated)<input value={domains} onChange={e=>{setDomains(e.target.value);setPage(1);}} placeholder="healthsystem.org"/></label><label>Buyer titles<input value={titles} onChange={e=>{setTitles(e.target.value);setPage(1);}}/></label><label>Locations (optional)<input value={locations} onChange={e=>{setLocations(e.target.value);setPage(1);}} placeholder="South Carolina, United States"/></label><label>Page<input type="number" min={1} max={500} value={page} onChange={e=>setPage(Number(e.target.value))}/></label></div>
    <div className="work-actions"><button disabled={!configured||busy||!domains.trim()} onClick={search}>{busy?'Working…':'Search Apollo'}</button><button disabled={busy||!chosen.length} onClick={save}>Save selected ({chosen.length})</button><button onClick={exportSaved} disabled={!saved.length}>Export saved prospects</button></div>
    {results.length>0?<div className="prospect-results"><p>Page {page} · {results.length} results · {total??'Unknown'} total matches</p>{results.map(p=><label key={p.id} className="prospect-result"><input type="checkbox" disabled={p.clientCheck?.status==="existing_client"||p.clientCheck?.status==="review"} checked={chosen.includes(p.id)} onChange={e=>setChosen(ids=>e.target.checked?[...ids,p.id]:ids.filter(id=>id!==p.id))}/><span><strong>{p.name}</strong> · {p.title}<small>{p.organization} · {p.domain||'Domain unavailable'} · {p.clientCheck?.reason}</small></span></label>)}</div>:null}
    <h3>Saved prospects ({saved.length})</h3>{!saved.length?<p>No prospects saved yet. Start with known healthcare accounts and review matching buyers.</p>:saved.map(p=><article className="saved-prospect" key={p.id}><div><strong>{p.name}</strong><p>{p.title} · {p.organization} · {p.domain}</p><small>Imported {new Date(p.importedAt).toLocaleDateString()} · Apollo ID {p.id} · {p.clientCheck?.reason}</small></div><label>Stage<select value={p.stage} onChange={e=>patch(p,{stage:e.target.value as Prospect['stage']})}>{PROSPECT_STAGES.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label>Notes<textarea key={`${p.id}-${p.version}`} defaultValue={p.notes} maxLength={5000} onBlur={e=>{if(e.target.value!==p.notes)patch(p,{notes:e.target.value});}}/></label></article>)}
  </section>;
}
